# Generated by Django 3.1.7 on 2021-03-03 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('youtubers', '0003_auto_20210301_2047'),
    ]

    operations = [
        migrations.RenameField(
            model_name='youtuber',
            old_name='firstname',
            new_name='fullname',
        ),
        migrations.RemoveField(
            model_name='youtuber',
            name='middlename',
        ),
        migrations.RemoveField(
            model_name='youtuber',
            name='surname',
        ),
    ]
